#################################
[Display Settings]
Resolution_Width = 3840

Resolution_Height = 2160

###### 1 = On, 0 = Off ###### 
MotionBlur = 1

###### 1 = On, 0 = Off ###### 
AmbientOcclusion = 1

###### 1 = On, 0 = Off ###### 
VSync = 1

###### 1 = On, 0 = Off ###### 
ReduceMouseLag = 1

###### 0 = Low, 1 = Medium, 2 = High, 3 = Ultra ###### 
TextureDetail = 3

###### 0 = Low, 1 = Medium, 2 = High, 3 = Ultra ###### 
ShadowDetail = 3

###### 0 = Off, 1 = Low, 2 = Medium, 3 = High ###### 
AntiAliasing = 3

###### 0 = Low, 1 = Medium, 2 = High, 3 = Ultra ###### 
DrawDistance = 3

###### 1 = Off, highest value is 16 ###### 
AnisotropicFiltering = 16

###### 0.0 = None, 1.0 = Full ###### 
Brightness = 0.203143

###### 1 = On, 0 = Off ###### 
Stereo3D = 0

###### 1 = On, 0 = Off ###### 
Stereo3DScoped = 0

###### 0.0 = None, 1.2 = Full ###### 
Stereo3DStrength = 1.000000

###### 0 = Off, 1 = On ###### 
ComputeShader = 1

###### 0 = Off, 1 = Low, 2 = Medium, 3 = High ###### 
AdvancedShadows = 3

###### 0 = Off, 1 = 2.25x, 2 = 4.0x ###### 
Supersampling = 1

